# Generated by Django 5.2.17 on 2026-09-27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("providers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider_name_snapshot", models.CharField(max_length=150)),
                ("service_title_snapshot", models.CharField(max_length=150)),
                (
                    "price_snapshot",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("currency_snapshot", models.CharField(max_length=3)),
                ("duration_minutes_snapshot", models.PositiveSmallIntegerField()),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("COMPLETED", "Completed"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No show"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "patient_note",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to="providers.providerprofile",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to="providers.serviceoffering",
                    ),
                ),
            ],
            options={
                "db_table": "reservations_reservation",
                "ordering": ["-starts_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "status", "starts_at"],
                        name="reservations_patient_idx",
                    ),
                    models.Index(
                        fields=["provider", "status", "starts_at"],
                        name="reservations_provider_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                        name="reservations_end_after_start",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("duration_minutes_snapshot__gt", 0)),
                        name="reservations_duration_positive",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReservationTransition",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("COMPLETED", "Completed"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No show"),
                        ],
                        default="",
                        max_length=12,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("COMPLETED", "Completed"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No show"),
                        ],
                        max_length=12,
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=500)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="reservations.reservation",
                    ),
                ),
            ],
            options={
                "db_table": "reservations_transition",
                "ordering": ["created_at"],
            },
        ),
    ]
