# Generated by Django 5.2.17 on 2026-09-28 19:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0002_seed_iraq'),
        ('specialties', '0002_seed_specialties'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCompany',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('public_email', models.EmailField(blank=True, default='', max_length=254)),
                ('website', models.URLField(blank=True, default='')),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='UNVERIFIED', max_length=16)),
                ('verification_note', models.TextField(blank=True, default='')),
                ('verification_requested_at', models.DateTimeField(blank=True, null=True)),
                ('verification_changed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_company', to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medical_companies', to='geography.city')),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_companies', to='geography.governorate')),
            ],
            options={
                'db_table': 'marketplace_company',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='marketplace.productcategory')),
            ],
            options={
                'verbose_name_plural': 'product categories',
                'db_table': 'marketplace_category',
                'ordering': ['sort_order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='ProductAudience',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_type', models.CharField(blank=True, choices=[('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('THERAPIST', 'Therapist'), ('HOSPITAL', 'Hospital'), ('MEDICAL_CENTER', 'Medical center'), ('PHARMACY', 'Pharmacy'), ('LABORATORY', 'Laboratory'), ('BEAUTY_CENTER', 'Beauty center')], default='', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_audiences', to='specialties.specialty')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiences', to='marketplace.productcategory')),
            ],
            options={
                'db_table': 'marketplace_audience',
                'ordering': ['category', 'provider_type', 'specialty_id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('brand', models.CharField(blank=True, default='', max_length=100)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='IQD', max_length=3)),
                ('is_active', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='marketplace.medicalcompany')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='marketplace.productcategory')),
            ],
            options={
                'db_table': 'marketplace_product',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='medicalcompany',
            index=models.Index(fields=['verification_status'], name='marketplace_company_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='productaudience',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('provider_type', ''), _negated=True), ('specialty__isnull', False), _connector='OR'), name='marketplace_audience_meaningful'),
        ),
        migrations.AddConstraint(
            model_name='productaudience',
            constraint=models.UniqueConstraint(fields=('category', 'provider_type', 'specialty'), name='marketplace_audience_unique', nulls_distinct=False),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'is_active'], name='marketplace_product_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='marketplace_product_cat_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price__isnull', True), ('price__gte', 0), _connector='OR'), name='marketplace_product_price_non_negative'),
        ),
    ]
