# Generated by Django 5.2.17 on 2026-10-01 14:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('RESERVATION', 'Reservation')], max_length=32)),
                ('event_type', models.CharField(choices=[('RESERVATION_CREATED', 'Reservation created'), ('RESERVATION_STATUS_CHANGED', 'Reservation status changed')], max_length=48)),
                ('resource_type', models.CharField(blank=True, choices=[('RESERVATION', 'Reservation')], default='', max_length=32)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(editable=False, max_length=200)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='notif_recipient_read_idx'), models.Index(fields=['recipient', '-created_at'], name='notif_recipient_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('dedupe_key',), name='notification_dedupe_key_unique'), models.CheckConstraint(condition=models.Q(models.Q(('resource_type', ''), ('resource_id__isnull', True)), models.Q(models.Q(('resource_type', ''), _negated=True), ('resource_id__isnull', False)), _connector='OR'), name='notification_resource_coherent')],
            },
        ),
    ]
