# Generated by Django 5.2.17 on 2026-10-07 05:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_push_device"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pushdevice",
            name="ownership_seq",
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name="pushdevice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ownership_seq__isnull", True),
                    ("ownership_seq__gt", 0),
                    _connector="OR",
                ),
                name="push_device_ownership_seq_positive",
            ),
        ),
    ]
