# Generated by Django 5.2.17 on 2026-09-23 16:11

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        ('specialties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_type', models.CharField(choices=[('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('THERAPIST', 'Therapist'), ('HOSPITAL', 'Hospital'), ('MEDICAL_CENTER', 'Medical center'), ('PHARMACY', 'Pharmacy'), ('LABORATORY', 'Laboratory'), ('BEAUTY_CENTER', 'Beauty center')], max_length=32)),
                ('display_name', models.CharField(max_length=150)),
                ('about', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('public_email', models.EmailField(blank=True, default='', max_length=254)),
                ('website', models.URLField(blank=True, default='')),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('image_url', models.URLField(blank=True, default='')),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='UNVERIFIED', max_length=16)),
                ('verification_note', models.TextField(blank=True, default='')),
                ('verification_requested_at', models.DateTimeField(blank=True, null=True)),
                ('verification_changed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='providers', to='geography.city')),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='providers', to='geography.governorate')),
                ('specialties', models.ManyToManyField(blank=True, related_name='providers', to='specialties.specialty')),
            ],
            options={
                'db_table': 'providers_profile',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='ProviderMembership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('ENDED', 'Ended')], default='PENDING', max_length=16)),
                ('initiated_by', models.CharField(choices=[('PRACTITIONER', 'Practitioner'), ('FACILITY', 'Facility')], max_length=16)),
                ('role_title', models.CharField(blank=True, default='', max_length=100)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_memberships', to='providers.providerprofile')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_memberships', to='providers.providerprofile')),
            ],
            options={
                'db_table': 'providers_membership',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOffering',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='IQD', max_length=3)),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='providers.providerprofile')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='specialties.specialty')),
            ],
            options={
                'db_table': 'providers_service',
                'ordering': ['title'],
            },
        ),
        migrations.AddIndex(
            model_name='providerprofile',
            index=models.Index(fields=['verification_status', 'is_visible', 'provider_type'], name='providers_profile_discover_idx'),
        ),
        migrations.AddIndex(
            model_name='providerprofile',
            index=models.Index(fields=['governorate', 'city'], name='providers_profile_geo_idx'),
        ),
        migrations.AddConstraint(
            model_name='providerprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__gte', -90), ('latitude__lte', 90), ('longitude__gte', -180), ('longitude__lte', 180)), _connector='OR'), name='providers_profile_coordinates_valid'),
        ),
        migrations.AddConstraint(
            model_name='providerprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__isnull', False), ('longitude__isnull', False)), _connector='OR'), name='providers_profile_coordinates_both_or_none'),
        ),
        migrations.AddIndex(
            model_name='providermembership',
            index=models.Index(fields=['facility', 'status'], name='providers_membership_fac_idx'),
        ),
        migrations.AddIndex(
            model_name='providermembership',
            index=models.Index(fields=['practitioner', 'status'], name='providers_membership_prac_idx'),
        ),
        migrations.AddConstraint(
            model_name='providermembership',
            constraint=models.CheckConstraint(condition=models.Q(('practitioner', models.F('facility')), _negated=True), name='providers_membership_not_self'),
        ),
        migrations.AddConstraint(
            model_name='providermembership',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'ACTIVE'])), fields=('practitioner', 'facility'), name='providers_membership_one_live_per_pair'),
        ),
        migrations.AddIndex(
            model_name='serviceoffering',
            index=models.Index(fields=['provider', 'is_active'], name='providers_service_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceoffering',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='providers_service_price_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='serviceoffering',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__isnull', True), ('duration_minutes__gt', 0), _connector='OR'), name='providers_service_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='serviceoffering',
            constraint=models.UniqueConstraint(fields=('provider', 'title'), name='providers_service_title_unique_per_provider'),
        ),
    ]
