# Generated by Django 5.2.17 on 2026-09-23 20:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, help_text='dotted code, e.g. billing.subscription.activated', max_length=80)),
                ('target_type', models.CharField(max_length=60)),
                ('target_id', models.CharField(max_length=64)),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id', '-created_at'], name='audit_event_target_idx')],
            },
        ),
    ]
