# Generated by Django 5.2.17 on 2026-09-23 20:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_type', models.CharField(choices=[('organization', 'Organisation'), ('account', 'Account')], max_length=20)),
                ('subject_id', models.UUIDField()),
                ('audience', models.CharField(choices=[('EMPLOYER', 'Employer organisation'), ('JOB_SEEKER', 'Job seeker')], max_length=20)),
            ],
            options={
                'db_table': 'billing_account',
                'constraints': [models.UniqueConstraint(fields=('subject_type', 'subject_id'), name='billing_account_subject_unique')],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=60)),
                ('delta', models.IntegerField()),
                ('reason', models.CharField(choices=[('GRANT', 'Administrator grant'), ('REVOKE', 'Administrator revoke'), ('CONSUME', 'Consumed by usage'), ('REFUND', 'Refund')], max_length=10)),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('billing_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='billing.billingaccount')),
            ],
            options={
                'db_table': 'billing_credit_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('audience', models.CharField(choices=[('EMPLOYER', 'Employer organisation'), ('JOB_SEEKER', 'Job seeker')], max_length=20)),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('description_ar', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('billing_period', models.CharField(choices=[('NONE', 'No renewal (default / trial)'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=12)),
                ('term_days', models.PositiveSmallIntegerField(default=30, help_text='Length of one subscription term')),
                ('price_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_currency', models.CharField(default='IQD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True, help_text='Shown to users as requestable')),
                ('is_default', models.BooleanField(default=False, help_text='Applies to subjects of this audience with no active subscription')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'billing_plan',
                'ordering': ['audience', 'sort_order', 'code'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('audience',), name='billing_plan_one_default_per_audience')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending administrator approval'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('REJECTED', 'Rejected')], default='PENDING', max_length=12)),
                ('requester_note', models.CharField(blank=True, default='', max_length=500)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('admin_reference', models.CharField(blank=True, default='', help_text='External payment/agreement reference', max_length=120)),
                ('admin_note', models.CharField(blank=True, default='', max_length=500)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('billing_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='billing.billingaccount')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_subscription',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='IQD', max_length=3)),
                ('method', models.CharField(choices=[('BANK_TRANSFER', 'Bank transfer'), ('CASH', 'Cash'), ('EXCHANGE_OFFICE', 'Exchange office'), ('OTHER', 'Other')], default='BANK_TRANSFER', max_length=20)),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('RECORDED', 'Recorded'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='RECORDED', max_length=10)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.subscription')),
            ],
            options={
                'db_table': 'billing_payment_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, default='', max_length=12)),
                ('to_status', models.CharField(max_length=12)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='billing.subscription')),
            ],
            options={
                'db_table': 'billing_subscription_event',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageCounter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=60)),
                ('period_start', models.DateField()),
                ('used', models.PositiveIntegerField(default=0)),
                ('billing_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='billing.billingaccount')),
            ],
            options={
                'db_table': 'billing_usage_counter',
            },
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=60)),
                ('amount', models.PositiveSmallIntegerField(default=1)),
                ('reference', models.CharField(blank=True, default='', max_length=160)),
                ('covered_by_credit', models.BooleanField(default=False)),
                ('billing_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='billing.billingaccount')),
            ],
            options={
                'db_table': 'billing_usage_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditBalance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=60)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('billing_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='billing.billingaccount')),
            ],
            options={
                'db_table': 'billing_credit_balance',
                'constraints': [models.UniqueConstraint(fields=('billing_account', 'key'), name='billing_credit_balance_unique')],
            },
        ),
        migrations.CreateModel(
            name='PlanEntitlement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=60)),
                ('kind', models.CharField(choices=[('BOOLEAN', 'Capability on/off'), ('LIMIT', 'Numeric limit')], max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('limit', models.PositiveIntegerField(blank=True, help_text='LIMIT kind: null = unlimited', null=True)),
                ('period', models.CharField(choices=[('NONE', 'Concurrent count (not consumed)'), ('DAILY', 'Per day'), ('MONTHLY', 'Per calendar month'), ('SUBSCRIPTION', 'Per subscription term')], default='NONE', max_length=14)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='billing.plan')),
            ],
            options={
                'db_table': 'billing_plan_entitlement',
                'ordering': ['key'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'key'), name='billing_plan_entitlement_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['billing_account', 'status'], name='billing_subscription_acc_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'ACTIVE'])), fields=('billing_account',), name='billing_subscription_one_live_per_account'),
        ),
        migrations.AddConstraint(
            model_name='usagecounter',
            constraint=models.UniqueConstraint(fields=('billing_account', 'key', 'period_start'), name='billing_usage_counter_unique'),
        ),
        migrations.AddConstraint(
            model_name='usageevent',
            constraint=models.UniqueConstraint(condition=models.Q(('reference', ''), _negated=True), fields=('billing_account', 'key', 'reference'), name='billing_usage_event_reference_unique'),
        ),
    ]
