# Generated by Django 5.2.17 on 2026-09-23 13:35

import apps.accounts.managers
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(blank=True, default='', max_length=32)),
                ('role', models.CharField(choices=[('PATIENT', 'Patient'), ('PROVIDER', 'Healthcare provider'), ('MEDICAL_COMPANY', 'Medical company / supplier'), ('REAL_ESTATE_SELLER', 'Medical real-estate owner or agent'), ('ADMIN', 'Racheeta administrator')], default='PATIENT', max_length=32)),
                ('preferred_language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='ar', max_length=2)),
                ('email_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Grants access to the Django admin site.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
                'db_table': 'accounts_account',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['role'], name='accounts_account_role_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='accounts_account_email_ci_unique'), models.UniqueConstraint(condition=models.Q(('phone_number', ''), _negated=True), fields=('phone_number',), name='accounts_account_phone_unique_when_set'), models.CheckConstraint(condition=models.Q(models.Q(('role', 'ADMIN'), _negated=True), ('is_staff', True), _connector='OR'), name='accounts_account_admin_role_requires_staff')],
            },
            managers=[
                ('objects', apps.accounts.managers.AccountManager()),
            ],
        ),
    ]
