# Generated by Django 5.2.17 on 2026-09-23, then edited to preserve data:
# the boolean `email_verified` becomes the timestamp `email_verified_at`.

from django.db import migrations, models
from django.utils import timezone


def carry_over_verified_flag(apps, schema_editor):
    Account = apps.get_model("accounts", "Account")
    Account.objects.filter(email_verified=True, email_verified_at__isnull=True).update(
        email_verified_at=timezone.now()
    )


def restore_verified_flag(apps, schema_editor):
    Account = apps.get_model("accounts", "Account")
    Account.objects.filter(email_verified_at__isnull=False).update(email_verified=True)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="email_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(carry_over_verified_flag, restore_verified_flag),
        migrations.RemoveField(
            model_name="account",
            name="email_verified",
        ),
        migrations.AddField(
            model_name="account",
            name="firebase_uid",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                condition=models.Q(("firebase_uid", ""), _negated=True),
                fields=("firebase_uid",),
                name="accounts_account_firebase_uid_unique_when_set",
            ),
        ),
    ]
