# Generated by Django 5.2.17 on 2026-09-23 20:14

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0002_seed_iraq'),
        ('providers', '0001_initial'),
        ('specialties', '0002_seed_specialties'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('REVIEWING', 'Reviewing'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW', 'Interview'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='SUBMITTED', max_length=12)),
                ('cover_text', models.TextField(blank=True, default='')),
                ('snapshot', models.JSONField(default=dict, help_text='Professional summary frozen at application time (no contact data)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'jobs_application',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Recruitment display name', max_length=150)),
                ('organization_type', models.CharField(choices=[('HOSPITAL', 'Hospital'), ('MEDICAL_CENTER', 'Medical center'), ('CLINIC', 'Clinic'), ('PHARMACY', 'Pharmacy'), ('LABORATORY', 'Laboratory'), ('BEAUTY_CENTER', 'Beauty center'), ('MEDICAL_COMPANY', 'Medical company'), ('HEALTHCARE_INSTITUTION', 'Healthcare institution'), ('UNIVERSITY', 'University / college'), ('RECRUITMENT_AGENCY', 'Recruitment agency'), ('OTHER', 'Other approved healthcare organisation')], max_length=32)),
                ('description', models.TextField(blank=True, default='')),
                ('is_recruitment_agency', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='UNVERIFIED', max_length=16)),
                ('verification_note', models.TextField(blank=True, default='')),
                ('verification_requested_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('recruitment_status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=12)),
                ('is_discoverable', models.BooleanField(default=True, help_text='Show the organisation page publicly')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employers', to='geography.city')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employers_created', to=settings.AUTH_USER_MODEL)),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employers', to='geography.governorate')),
                ('provider_profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer', to='providers.providerprofile')),
            ],
            options={
                'db_table': 'jobs_employer',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployerMembership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('RECRUITER', 'Recruiter'), ('VIEWER', 'Viewer')], default='RECRUITER', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ENDED', 'Ended')], default='ACTIVE', max_length=8)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_memberships', to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='jobs.employer')),
            ],
            options={
                'db_table': 'jobs_employer_membership',
            },
        ),
        migrations.CreateModel(
            name='InterviewRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposed_at', models.DateTimeField()),
                ('mode', models.CharField(choices=[('IN_PERSON', 'In person'), ('ONLINE', 'Online (details shared inside Racheeta)')], max_length=10)),
                ('location_text', models.CharField(blank=True, default='', max_length=255)),
                ('employer_note', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], default='PROPOSED', max_length=10)),
                ('candidate_response', models.CharField(blank=True, default='', max_length=500)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='jobs.jobapplication')),
            ],
            options={
                'db_table': 'jobs_interview_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplicationTransition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, default='', max_length=12)),
                ('to_status', models.CharField(max_length=12)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='jobs.jobapplication')),
            ],
            options={
                'db_table': 'jobs_application_transition',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hiring_organization_name', models.CharField(blank=True, default='', max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('profession', models.CharField(choices=[('DOCTOR', 'Physician'), ('DENTIST', 'Dentist'), ('PHARMACIST', 'Pharmacist'), ('NURSE', 'Nurse'), ('MIDWIFE', 'Midwife'), ('LAB_TECHNICIAN', 'Laboratory technician'), ('RADIOLOGY_TECHNICIAN', 'Radiology technician'), ('ANESTHESIA_TECHNICIAN', 'Anaesthesia technician'), ('PHYSIOTHERAPIST', 'Physiotherapist'), ('NUTRITIONIST', 'Nutritionist'), ('PSYCHOLOGIST', 'Psychologist'), ('MEDICAL_ASSISTANT', 'Medical assistant'), ('ADMINISTRATIVE', 'Administrative / reception'), ('OTHER', 'Other healthcare profession')], max_length=32)),
                ('detailed_specialty', models.CharField(blank=True, default='', max_length=150)),
                ('description', models.TextField()),
                ('responsibilities', models.TextField(blank=True, default='')),
                ('requirements', models.TextField(blank=True, default='')),
                ('minimum_degree', models.CharField(blank=True, choices=[('DIPLOMA', 'Diploma'), ('BACHELOR', 'Bachelor'), ('HIGHER_DIPLOMA', 'Higher diploma'), ('MASTER', 'Master'), ('PHD', 'PhD'), ('BOARD', 'Board certification'), ('OTHER', 'Other')], default='', max_length=16)),
                ('minimum_experience_years', models.PositiveSmallIntegerField(default=0)),
                ('workplace_text', models.CharField(blank=True, default='', max_length=150)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full time'), ('PART_TIME', 'Part time'), ('CONTRACT', 'Contract'), ('TEMPORARY', 'Temporary'), ('INTERNSHIP', 'Internship / residency'), ('LOCUM', 'Locum')], max_length=16)),
                ('work_mode', models.CharField(choices=[('ON_SITE', 'On site'), ('REMOTE', 'Remote'), ('HYBRID', 'Hybrid')], default='ON_SITE', max_length=8)),
                ('shift_type', models.CharField(blank=True, choices=[('DAY', 'Day'), ('NIGHT', 'Night'), ('ROTATING', 'Rotating'), ('FLEXIBLE', 'Flexible'), ('ON_CALL', 'On call')], default='', max_length=10)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_currency', models.CharField(default='IQD', max_length=3)),
                ('salary_visible', models.BooleanField(default=False)),
                ('number_of_openings', models.PositiveSmallIntegerField(default=1)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_ADMIN_REVIEW', 'Pending administrator review'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed'), ('EXPIRED', 'Expired'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=24)),
                ('moderation_note', models.TextField(blank=True, default='')),
                ('moderation_flags', models.JSONField(blank=True, default=list, help_text='Contact-leak findings at submission')),
                ('is_featured', models.BooleanField(default=False)),
                ('featured_until', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='geography.city')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs_created', to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.employer')),
                ('general_specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='specialties.specialty')),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='geography.governorate')),
                ('hiring_employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_hired_via_agency', to='jobs.employer')),
            ],
            options={
                'db_table': 'jobs_post',
                'ordering': ['-is_featured', '-published_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobpost'),
        ),
        migrations.CreateModel(
            name='JobPostTransition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, default='', max_length=24)),
                ('to_status', models.CharField(max_length=24)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='jobs.jobpost')),
            ],
            options={
                'db_table': 'jobs_post_transition',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('professional_title', models.CharField(max_length=150)),
                ('profession', models.CharField(choices=[('DOCTOR', 'Physician'), ('DENTIST', 'Dentist'), ('PHARMACIST', 'Pharmacist'), ('NURSE', 'Nurse'), ('MIDWIFE', 'Midwife'), ('LAB_TECHNICIAN', 'Laboratory technician'), ('RADIOLOGY_TECHNICIAN', 'Radiology technician'), ('ANESTHESIA_TECHNICIAN', 'Anaesthesia technician'), ('PHYSIOTHERAPIST', 'Physiotherapist'), ('NUTRITIONIST', 'Nutritionist'), ('PSYCHOLOGIST', 'Psychologist'), ('MEDICAL_ASSISTANT', 'Medical assistant'), ('ADMINISTRATIVE', 'Administrative / reception'), ('OTHER', 'Other healthcare profession')], max_length=32)),
                ('detailed_specialty', models.CharField(blank=True, default='', max_length=150)),
                ('degree', models.CharField(choices=[('DIPLOMA', 'Diploma'), ('BACHELOR', 'Bachelor'), ('HIGHER_DIPLOMA', 'Higher diploma'), ('MASTER', 'Master'), ('PHD', 'PhD'), ('BOARD', 'Board certification'), ('OTHER', 'Other')], max_length=16)),
                ('institution_name', models.CharField(blank=True, default='', max_length=150)),
                ('graduation_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('years_of_experience', models.PositiveSmallIntegerField(default=0)),
                ('professional_summary', models.TextField(blank=True, default='')),
                ('employment_preferences', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('FULL_TIME', 'Full time'), ('PART_TIME', 'Part time'), ('CONTRACT', 'Contract'), ('TEMPORARY', 'Temporary'), ('INTERNSHIP', 'Internship / residency'), ('LOCUM', 'Locum')], max_length=16), blank=True, default=list, size=None)),
                ('availability', models.CharField(choices=[('IMMEDIATE', 'Immediately'), ('WITHIN_MONTH', 'Within a month'), ('WITHIN_3_MONTHS', 'Within three months'), ('NOT_AVAILABLE', 'Not currently available')], default='WITHIN_MONTH', max_length=16)),
                ('salary_expectation_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_currency', models.CharField(default='IQD', max_length=3)),
                ('discoverable_by_employers', models.BooleanField(default=False)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_seeker_profile', to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_seekers', to='geography.city')),
                ('desired_governorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geography.governorate')),
                ('general_specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_seekers', to='specialties.specialty')),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_seekers', to='geography.governorate')),
            ],
            options={
                'db_table': 'jobs_seeker_profile',
            },
        ),
        migrations.CreateModel(
            name='JobInvitation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='jobs.employer')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='jobs.jobpost')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='jobs.jobseekerprofile')),
            ],
            options={
                'db_table': 'jobs_invitation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobseekerprofile'),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('degree', models.CharField(choices=[('DIPLOMA', 'Diploma'), ('BACHELOR', 'Bachelor'), ('HIGHER_DIPLOMA', 'Higher diploma'), ('MASTER', 'Master'), ('PHD', 'PhD'), ('BOARD', 'Board certification'), ('OTHER', 'Other')], max_length=16)),
                ('field_of_study', models.CharField(max_length=150)),
                ('institution_name', models.CharField(max_length=150)),
                ('start_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='jobs.jobseekerprofile')),
            ],
            options={
                'db_table': 'jobs_seeker_education',
                'ordering': ['-end_year'],
            },
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('LICENSE', 'Professional licence'), ('CERTIFICATION', 'Training / certification')], max_length=14)),
                ('name', models.CharField(max_length=150)),
                ('issuer', models.CharField(blank=True, default='', max_length=150)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='jobs.jobseekerprofile')),
            ],
            options={
                'db_table': 'jobs_seeker_credential',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='LanguageSkill',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(help_text='e.g. Arabic, English, Kurdish', max_length=40)),
                ('language_normalized', models.CharField(db_index=True, editable=False, max_length=40)),
                ('level', models.CharField(choices=[('BASIC', 'Basic'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('NATIVE', 'Native')], max_length=12)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='jobs.jobseekerprofile')),
            ],
            options={
                'db_table': 'jobs_seeker_language',
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='RecruitmentMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_side', models.CharField(choices=[('EMPLOYER', 'Employer'), ('CANDIDATE', 'Candidate')], max_length=10)),
                ('body', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='jobs.jobapplication')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs_recruitment_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedCandidate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.CharField(blank=True, default='', help_text='Private to the employer; never shown to the candidate', max_length=500)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_candidates', to='jobs.employer')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='jobs.jobseekerprofile')),
            ],
            options={
                'db_table': 'jobs_saved_candidate',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('name_normalized', models.CharField(db_index=True, editable=False, max_length=80)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='jobs.jobseekerprofile')),
            ],
            options={
                'db_table': 'jobs_seeker_skill',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TalentSearchQuery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signature', models.CharField(max_length=64)),
                ('day', models.DateField()),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_searches', to='jobs.employer')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs_talent_search_query',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('organization_name', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
                ('governorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geography.governorate')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='jobs.jobseekerprofile')),
            ],
            options={
                'db_table': 'jobs_seeker_experience',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='employer',
            index=models.Index(fields=['verification_status', 'recruitment_status'], name='jobs_employer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='employermembership',
            index=models.Index(fields=['employer', 'status'], name='jobs_membership_employer_idx'),
        ),
        migrations.AddConstraint(
            model_name='employermembership',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('account',), name='jobs_membership_one_active_per_account'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['status', '-is_featured', '-published_at'], name='jobs_post_public_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['employer', 'status'], name='jobs_post_employer_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['profession', 'governorate'], name='jobs_post_prof_geo_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['application_deadline'], name='jobs_post_deadline_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobpost',
            constraint=models.CheckConstraint(condition=models.Q(('salary_min__isnull', True), ('salary_max__isnull', True), ('salary_min__lte', models.F('salary_max')), _connector='OR'), name='jobs_post_salary_range'),
        ),
        migrations.AddConstraint(
            model_name='jobpost',
            constraint=models.CheckConstraint(condition=models.Q(('number_of_openings__gte', 1)), name='jobs_post_openings_positive'),
        ),
        migrations.AddIndex(
            model_name='jobseekerprofile',
            index=models.Index(fields=['discoverable_by_employers', 'profession'], name='jobs_seeker_discover_idx'),
        ),
        migrations.AddIndex(
            model_name='jobseekerprofile',
            index=models.Index(fields=['governorate', 'city'], name='jobs_seeker_geo_idx'),
        ),
        migrations.AddIndex(
            model_name='jobseekerprofile',
            index=models.Index(fields=['degree', 'years_of_experience'], name='jobs_seeker_degree_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='jobinvitation',
            index=models.Index(fields=['job_seeker', 'status'], name='jobs_invitation_seeker_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('job', 'job_seeker'), name='jobs_invitation_one_pending_per_job'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['job', 'status'], name='jobs_application_job_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['job_seeker', 'status'], name='jobs_application_seeker_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['SUBMITTED', 'REVIEWING', 'SHORTLISTED', 'INTERVIEW', 'ACCEPTED'])), fields=('job', 'job_seeker'), name='jobs_application_one_active_per_job'),
        ),
        migrations.AddConstraint(
            model_name='languageskill',
            constraint=models.UniqueConstraint(fields=('profile', 'language_normalized'), name='jobs_seeker_language_unique'),
        ),
        migrations.AddIndex(
            model_name='recruitmentmessage',
            index=models.Index(fields=['application', 'created_at'], name='jobs_message_app_idx'),
        ),
        migrations.AddConstraint(
            model_name='savedcandidate',
            constraint=models.UniqueConstraint(fields=('employer', 'job_seeker'), name='jobs_saved_candidate_unique'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('profile', 'name_normalized'), name='jobs_seeker_skill_unique'),
        ),
        migrations.AddConstraint(
            model_name='talentsearchquery',
            constraint=models.UniqueConstraint(fields=('employer', 'signature', 'day'), name='jobs_talent_search_unique_per_day'),
        ),
    ]
