# Generated by Django 5.2.17 on 2026-09-30 11:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0002_seed_iraq'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateSeller',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seller_type', models.CharField(choices=[('OWNER', 'Owner'), ('AGENT', 'Agent')], max_length=8)),
                ('display_name', models.CharField(max_length=150)),
                ('about', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('public_email', models.EmailField(blank=True, default='', max_length=254)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'real_estate_seller',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('property_type', models.CharField(choices=[('CLINIC', 'Clinic'), ('APARTMENT_FOR_CLINIC', 'Apartment suitable for a clinic'), ('MEDICAL_BUILDING', 'Medical building'), ('PHARMACY_LOCATION', 'Pharmacy location'), ('LABORATORY_LOCATION', 'Laboratory location'), ('MEDICAL_CENTER', 'Medical center'), ('HOSPITAL_BUILDING', 'Hospital building'), ('COMMERCIAL_MEDICAL_PROPERTY', 'Commercial property suitable for medical use'), ('MEDICAL_INVESTMENT_LAND', 'Land for medical investment')], max_length=32)),
                ('transaction_type', models.CharField(choices=[('SALE', 'Sale'), ('RENT', 'Rent')], max_length=8)),
                ('district', models.CharField(blank=True, default='', max_length=150)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='IQD', max_length=3)),
                ('facilities', models.TextField(blank=True, default='')),
                ('contact_method', models.CharField(choices=[('PHONE', 'Phone'), ('EMAIL', 'Email'), ('BOTH', 'Phone and email')], default='PHONE', max_length=8)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=32)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('publication_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_listings', to='geography.city')),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_listings', to='geography.governorate')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='real_estate.realestateseller')),
            ],
            options={
                'db_table': 'real_estate_listing',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ListingSuitableUse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('use', models.CharField(choices=[('CLINIC', 'Clinic'), ('PHARMACY', 'Pharmacy'), ('LABORATORY', 'Laboratory'), ('MEDICAL_CENTER', 'Medical center'), ('HOSPITAL', 'Hospital'), ('GENERAL_MEDICAL_USE', 'General medical use'), ('MEDICAL_INVESTMENT', 'Medical investment')], max_length=24)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suitable_uses', to='real_estate.propertylisting')),
            ],
            options={
                'db_table': 'real_estate_listing_use',
                'ordering': ['listing_id', 'use'],
                'indexes': [models.Index(fields=['use'], name='real_estate_use_idx')],
                'constraints': [models.UniqueConstraint(fields=('listing', 'use'), name='real_estate_listing_use_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='propertylisting',
            index=models.Index(fields=['seller', 'publication_status'], name='real_estate_seller_status'),
        ),
        migrations.AddIndex(
            model_name='propertylisting',
            index=models.Index(fields=['publication_status', 'expires_at'], name='real_estate_status_expiry'),
        ),
        migrations.AddIndex(
            model_name='propertylisting',
            index=models.Index(fields=['publication_status', 'transaction_type'], name='real_estate_status_txn'),
        ),
        migrations.AddIndex(
            model_name='propertylisting',
            index=models.Index(fields=['publication_status', 'property_type'], name='real_estate_status_ptype'),
        ),
        migrations.AddIndex(
            model_name='propertylisting',
            index=models.Index(fields=['governorate', 'city'], name='real_estate_geo_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertylisting',
            constraint=models.CheckConstraint(condition=models.Q(('price__isnull', True), ('price__gte', 0), _connector='OR'), name='real_estate_listing_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='propertylisting',
            constraint=models.CheckConstraint(condition=models.Q(('area_sqm__isnull', True), ('area_sqm__gt', 0), _connector='OR'), name='real_estate_listing_area_positive'),
        ),
        migrations.AddConstraint(
            model_name='propertylisting',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__isnull', True), models.Q(('latitude__gte', -90), ('latitude__lte', 90)), _connector='OR'), name='real_estate_listing_latitude_range'),
        ),
        migrations.AddConstraint(
            model_name='propertylisting',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__isnull', True), models.Q(('longitude__gte', -180), ('longitude__lte', 180)), _connector='OR'), name='real_estate_listing_longitude_range'),
        ),
        migrations.AddConstraint(
            model_name='propertylisting',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__isnull', False), ('longitude__isnull', False)), _connector='OR'), name='real_estate_listing_coordinate_pair'),
        ),
        migrations.AddConstraint(
            model_name='propertylisting',
            constraint=models.CheckConstraint(condition=models.Q(('publication_status', 'DRAFT'), models.Q(('area_sqm__isnull', False), ('expires_at__isnull', False)), _connector='OR'), name='real_estate_listing_published_complete'),
        ),
    ]
