# Generated by Django 5.2 for Racheeta Phase 9B.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, editable=False)),
                (
                    "context_type",
                    models.CharField(
                        choices=[("RESERVATION", "Reservation")],
                        max_length=32,
                    ),
                ),
                ("context_id", models.UUIDField()),
                ("last_sequence", models.PositiveBigIntegerField(default=0, editable=False)),
                ("last_message_at", models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                "db_table": "chat_conversation",
                "ordering": ["-last_message_at", "-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["context_type", "context_id"],
                        name="chat_context_lookup_idx",
                    ),
                    models.Index(fields=["-last_message_at"], name="chat_last_message_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("context_type", "context_id"),
                        name="chat_conversation_context_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ConversationParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, editable=False)),
                ("last_read_sequence", models.PositiveBigIntegerField(default=0)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chat_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="chat.conversation",
                    ),
                ),
            ],
            options={
                "db_table": "chat_conversation_participant",
                "indexes": [
                    models.Index(
                        fields=["account", "conversation"],
                        name="chat_participant_account_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("conversation", "account"),
                        name="chat_participant_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, editable=False)),
                ("sequence", models.PositiveBigIntegerField(editable=False)),
                ("body", models.TextField(max_length=2000)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.conversation",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_message",
                "ordering": ["sequence"],
                "indexes": [
                    models.Index(
                        fields=["conversation", "-sequence"],
                        name="chat_message_thread_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("conversation", "sequence"),
                        name="chat_message_sequence_unique",
                    )
                ],
            },
        ),
    ]
