# Generated by Django 5.2.17 on 2026-09-30 16:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0002_seed_iraq'),
        ('marketplace', '0001_initial'),
        ('specialties', '0002_seed_specialties'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisingRate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='IQD', max_length=3)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'advertising_rate',
                'ordering': ['-is_active', 'code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('price_per_day__gt', 0)), name='advertising_rate_price_positive'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='advertising_rate_one_active')],
            },
        ),
        migrations.CreateModel(
            name='AdvertisingCampaign',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_PAYMENT', 'Pending payment verification'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('quoted_days', models.PositiveIntegerField(blank=True, null=True)),
                ('quoted_daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('quoted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('quoted_currency', models.CharField(blank=True, default='', max_length=3)),
                ('quoted_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advertising_campaigns', to='marketplace.medicalcompany')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advertising_campaigns', to='marketplace.product')),
                ('rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='advertising.advertisingrate')),
            ],
            options={
                'db_table': 'advertising_campaign',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CampaignGovernorate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_governorates', to='advertising.advertisingcampaign')),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advertising_targets', to='geography.governorate')),
            ],
            options={
                'db_table': 'advertising_campaign_governorate',
                'ordering': ['campaign_id', 'governorate_id'],
            },
        ),
        migrations.CreateModel(
            name='CampaignPayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('method', models.CharField(blank=True, choices=[('BANK_TRANSFER', 'Bank transfer'), ('CASH', 'Cash'), ('EXCHANGE_OFFICE', 'Exchange office'), ('OTHER', 'Other')], default='', max_length=20)),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='advertising.advertisingcampaign')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'advertising_payment',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CampaignProviderType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_type', models.CharField(choices=[('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('THERAPIST', 'Therapist'), ('HOSPITAL', 'Hospital'), ('MEDICAL_CENTER', 'Medical center'), ('PHARMACY', 'Pharmacy'), ('LABORATORY', 'Laboratory'), ('BEAUTY_CENTER', 'Beauty center')], max_length=32)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_provider_types', to='advertising.advertisingcampaign')),
            ],
            options={
                'db_table': 'advertising_campaign_provider_type',
                'ordering': ['campaign_id', 'provider_type'],
            },
        ),
        migrations.CreateModel(
            name='CampaignSpecialty',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_specialties', to='advertising.advertisingcampaign')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advertising_targets', to='specialties.specialty')),
            ],
            options={
                'db_table': 'advertising_campaign_specialty',
                'ordering': ['campaign_id', 'specialty_id'],
            },
        ),
        migrations.AddIndex(
            model_name='advertisingcampaign',
            index=models.Index(fields=['company', 'status'], name='advertising_campaign_co_status'),
        ),
        migrations.AddIndex(
            model_name='advertisingcampaign',
            index=models.Index(fields=['status', 'starts_on', 'ends_on'], name='advertising_campaign_window'),
        ),
        migrations.AddConstraint(
            model_name='advertisingcampaign',
            constraint=models.CheckConstraint(condition=models.Q(('starts_on__isnull', True), ('ends_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='advertising_campaign_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='advertisingcampaign',
            constraint=models.CheckConstraint(condition=models.Q(('quoted_amount__isnull', True), ('quoted_amount__gte', 0), _connector='OR'), name='advertising_campaign_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='advertisingcampaign',
            constraint=models.CheckConstraint(condition=models.Q(('quoted_days__isnull', True), ('quoted_days__gt', 0), _connector='OR'), name='advertising_campaign_days_positive'),
        ),
        migrations.AddConstraint(
            model_name='advertisingcampaign',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'DRAFT'), models.Q(('starts_on__isnull', False), ('ends_on__isnull', False), ('quoted_days__isnull', False), ('quoted_daily_rate__isnull', False), ('quoted_amount__isnull', False), ('quoted_at__isnull', False), models.Q(('quoted_currency', ''), _negated=True)), _connector='OR'), name='advertising_campaign_submitted_has_quote'),
        ),
        migrations.AddConstraint(
            model_name='campaigngovernorate',
            constraint=models.UniqueConstraint(fields=('campaign', 'governorate'), name='advertising_campaign_governorate_unique'),
        ),
        migrations.AddConstraint(
            model_name='campaignpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='advertising_payment_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='campaignpayment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'VERIFIED'), ('verified_at__isnull', False), models.Q(('method', ''), _negated=True)), models.Q(models.Q(('status', 'VERIFIED'), _negated=True), ('verified_at__isnull', True)), _connector='OR'), name='advertising_payment_verified_coherent'),
        ),
        migrations.AddConstraint(
            model_name='campaignprovidertype',
            constraint=models.UniqueConstraint(fields=('campaign', 'provider_type'), name='advertising_campaign_ptype_unique'),
        ),
        migrations.AddConstraint(
            model_name='campaignspecialty',
            constraint=models.UniqueConstraint(fields=('campaign', 'specialty'), name='advertising_campaign_specialty_unique'),
        ),
    ]
