"""Initial specialties used by migration 0002. Edit only via a new migration."""

# (slug, name_en, name_ar, parent_slug)
SPECIALTIES = [
    ("general-medicine", "General Medicine", "الطب العام", None),
    ("family-medicine", "Family Medicine", "طب الأسرة", None),
    ("internal-medicine", "Internal Medicine", "الطب الباطني", None),
    ("cardiology", "Cardiology", "أمراض القلب", None),
    ("dermatology", "Dermatology", "الأمراض الجلدية", None),
    ("pediatrics", "Pediatrics", "طب الأطفال", None),
    ("orthopedics", "Orthopedics", "جراحة العظام", None),
    ("general-surgery", "General Surgery", "الجراحة العامة", None),
    ("obstetrics-gynecology", "Obstetrics & Gynecology", "النسائية والتوليد", None),
    ("ophthalmology", "Ophthalmology", "طب العيون", None),
    ("ent", "Ear, Nose & Throat", "الأنف والأذن والحنجرة", None),
    ("neurology", "Neurology", "الأمراض العصبية", None),
    ("psychiatry", "Psychiatry", "الطب النفسي", None),
    ("urology", "Urology", "المسالك البولية", None),
    ("nephrology", "Nephrology", "أمراض الكلى", None),
    ("oncology", "Oncology", "الأورام", None),
    ("endocrinology", "Endocrinology", "الغدد الصماء والسكري", None),
    ("gastroenterology", "Gastroenterology", "الجهاز الهضمي", None),
    ("radiology", "Radiology", "الأشعة", None),
    ("anesthesiology", "Anesthesiology", "التخدير", None),
    ("dentistry", "Dentistry", "طب الأسنان", None),
    ("orthodontics", "Orthodontics", "تقويم الأسنان", "dentistry"),
    ("oral-surgery", "Oral & Maxillofacial Surgery", "جراحة الفم والوجه والفكين", "dentistry"),
    ("physiotherapy", "Physiotherapy", "العلاج الطبيعي", None),
    ("nursing", "Nursing", "التمريض", None),
    ("laboratory-medicine", "Laboratory Medicine", "المختبرات الطبية", None),
    ("nutrition", "Nutrition & Dietetics", "التغذية", None),
    ("aesthetic-medicine", "Aesthetic Medicine", "الطب التجميلي", None),
    ("pharmacy", "Pharmacy", "الصيدلة", None),
]
