"""Initial plan configuration (reference data). Prices are intentionally
unset: the owner sets them in the admin. Limits are conservative and
administrator-editable without code changes."""

from .types import Audience, BillingPeriod, Keys

B, L = "BOOLEAN", "LIMIT"

# (code, audience, name_en, name_ar, period, term_days, is_public, is_default, sort, entitlements)
# entitlement: (key, kind, enabled, limit, usage_period)
PLANS = [
    (
        "TRIAL",
        Audience.EMPLOYER,
        "Trial",
        "تجريبي",
        BillingPeriod.NONE,
        0,
        False,
        True,
        0,
        [
            (Keys.JOBS_POST, B, True, None, "NONE"),
            (Keys.JOBS_ACTIVE_LIMIT, L, True, 1, "NONE"),
            (Keys.JOBS_APPLICATION_REVIEW, B, True, None, "NONE"),
            (Keys.TALENT_SEARCH, B, False, None, "NONE"),
            (Keys.TALENT_INVITE, B, False, None, "NONE"),
            (Keys.TALENT_SAVE, B, False, None, "NONE"),
            (Keys.RECRUITER_SEATS, L, True, 1, "NONE"),
            (Keys.RECRUITMENT_MESSAGING, B, True, None, "NONE"),
            (Keys.JOBS_FEATURED, B, False, None, "NONE"),
        ],
    ),
    (
        "BASIC",
        Audience.EMPLOYER,
        "Basic",
        "أساسي",
        BillingPeriod.MONTHLY,
        30,
        True,
        False,
        1,
        [
            (Keys.JOBS_POST, B, True, None, "NONE"),
            (Keys.JOBS_ACTIVE_LIMIT, L, True, 3, "NONE"),
            (Keys.JOBS_APPLICATION_REVIEW, B, True, None, "NONE"),
            (Keys.TALENT_SEARCH, B, True, None, "NONE"),
            (Keys.TALENT_SEARCH_LIMIT, L, True, 20, "MONTHLY"),
            (Keys.TALENT_INVITE, B, True, None, "NONE"),
            (Keys.TALENT_INVITE_LIMIT, L, True, 10, "MONTHLY"),
            (Keys.TALENT_SAVE, B, True, None, "NONE"),
            (Keys.RECRUITER_SEATS, L, True, 2, "NONE"),
            (Keys.RECRUITMENT_MESSAGING, B, True, None, "NONE"),
            (Keys.JOBS_FEATURED, B, False, None, "NONE"),
        ],
    ),
    (
        "PROFESSIONAL",
        Audience.EMPLOYER,
        "Professional",
        "احترافي",
        BillingPeriod.MONTHLY,
        30,
        True,
        False,
        2,
        [
            (Keys.JOBS_POST, B, True, None, "NONE"),
            (Keys.JOBS_ACTIVE_LIMIT, L, True, 10, "NONE"),
            (Keys.JOBS_APPLICATION_REVIEW, B, True, None, "NONE"),
            (Keys.TALENT_SEARCH, B, True, None, "NONE"),
            (Keys.TALENT_SEARCH_LIMIT, L, True, 100, "MONTHLY"),
            (Keys.TALENT_INVITE, B, True, None, "NONE"),
            (Keys.TALENT_INVITE_LIMIT, L, True, 50, "MONTHLY"),
            (Keys.TALENT_SAVE, B, True, None, "NONE"),
            (Keys.RECRUITER_SEATS, L, True, 5, "NONE"),
            (Keys.RECRUITMENT_MESSAGING, B, True, None, "NONE"),
            (Keys.JOBS_FEATURED, B, True, None, "NONE"),
            (Keys.JOBS_FEATURED_LIMIT, L, True, 2, "NONE"),
        ],
    ),
    (
        "BUSINESS",
        Audience.EMPLOYER,
        "Business",
        "أعمال",
        BillingPeriod.MONTHLY,
        30,
        True,
        False,
        3,
        [
            (Keys.JOBS_POST, B, True, None, "NONE"),
            (Keys.JOBS_ACTIVE_LIMIT, L, True, 30, "NONE"),
            (Keys.JOBS_APPLICATION_REVIEW, B, True, None, "NONE"),
            (Keys.TALENT_SEARCH, B, True, None, "NONE"),
            (Keys.TALENT_SEARCH_LIMIT, L, True, 500, "MONTHLY"),
            (Keys.TALENT_INVITE, B, True, None, "NONE"),
            (Keys.TALENT_INVITE_LIMIT, L, True, 200, "MONTHLY"),
            (Keys.TALENT_SAVE, B, True, None, "NONE"),
            (Keys.RECRUITER_SEATS, L, True, 15, "NONE"),
            (Keys.RECRUITMENT_MESSAGING, B, True, None, "NONE"),
            (Keys.JOBS_FEATURED, B, True, None, "NONE"),
            (Keys.JOBS_FEATURED_LIMIT, L, True, 5, "NONE"),
        ],
    ),
    (
        "ENTERPRISE",
        Audience.EMPLOYER,
        "Enterprise",
        "مؤسسات",
        BillingPeriod.YEARLY,
        365,
        True,
        False,
        4,
        [
            (Keys.JOBS_POST, B, True, None, "NONE"),
            (Keys.JOBS_ACTIVE_LIMIT, L, True, None, "NONE"),
            (Keys.JOBS_APPLICATION_REVIEW, B, True, None, "NONE"),
            (Keys.TALENT_SEARCH, B, True, None, "NONE"),
            (Keys.TALENT_SEARCH_LIMIT, L, True, None, "MONTHLY"),
            (Keys.TALENT_INVITE, B, True, None, "NONE"),
            (Keys.TALENT_INVITE_LIMIT, L, True, None, "MONTHLY"),
            (Keys.TALENT_SAVE, B, True, None, "NONE"),
            (Keys.RECRUITER_SEATS, L, True, None, "NONE"),
            (Keys.RECRUITMENT_MESSAGING, B, True, None, "NONE"),
            (Keys.JOBS_FEATURED, B, True, None, "NONE"),
            (Keys.JOBS_FEATURED_LIMIT, L, True, None, "NONE"),
        ],
    ),
    (
        "SEEKER_FREE",
        Audience.JOB_SEEKER,
        "Job seeker (free)",
        "باحث عن عمل (مجاني)",
        BillingPeriod.NONE,
        0,
        False,
        True,
        0,
        [(Keys.APPLICATIONS_LIMIT, L, True, 15, "MONTHLY")],
    ),
    (
        "SEEKER_PLUS",
        Audience.JOB_SEEKER,
        "Job seeker plus",
        "باحث عن عمل بلس",
        BillingPeriod.MONTHLY,
        30,
        True,
        False,
        1,
        [(Keys.APPLICATIONS_LIMIT, L, True, None, "MONTHLY")],
    ),
]
